# .goreleaser.yml
project_name: hypodeigma
release:
  github:
    owner: dasdachs
    name: https://github.com/dasdachs/hypodeigma
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - 386
archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'